# Generated by Django 4.2 on 2023-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="image vide", null=True, upload_to="images/"
            ),
        ),
    ]
